plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ohgiraffers'
version = '0.0.1-SNAPSHOT'

/* 설명. java 플러그인이 제공하는 자바 빌드 설정 영역이다. */
java {
    /* 설명. 툴체인은 IDE나 JAVA_HOME과 무관하게, 이 프로젝트를 빌드·실행할 JDK를 Gradle이 직접 골라 쓰게 하는 기능이다. */
    toolchain {
        /* 설명. 해당 프로젝트에서 사용할 JDK 버전을 명시. */
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
